# Slides

In [ ]:
print("hello world")

In [ ]:
name = input("What's your name?")
print('Hello', name)

In [ ]:
print(name)

In [ ]:
length = int(input("Enter length: "))
breadth = int(input("Enter breadth:"))

print('Area:' + str(length*breadth))

#Another way to print using f-string
print(f'Area: {length*breadth:.2f}')

In [ ]:
weight = float(input("Enter your weight: "))
height = float(input("Enter your height: "))
bmi = weight/(height*height)
print(f'Your bmi is {bmi}')

print(f'Your bmi is {bmi:.2f}')

print(f'Your Height is {height}, weight is {weight} and BMI is {bmi:.4f}')

In [ ]:
# This example shows you how to write a comment
# The code below prompts the user to enter his current age
# and automatically computes the year he was born

age = int(input('Enter your age this year: '))
year_of_birth = 2020 - age
print(f"You were born in the year {year_of_birth} ")

In [2]:
import math

x = 349.4378

print(math.isnan(x)) # returns True if x is NOT a number
print(math.ceil(x)) # round x upwards  output: 350
print(math.floor(x)) # round x downwards  output: 349
print(math.sqrt(x)) # square root of x  output: 18.693255468216336


False
350
349
18.693255468216336


In [4]:
s = 'hi how are you'
print(s[0]) # this extracts the character with index 0  h
print(s[1])   # this extracts the character with index 1  i
print(s[3:6])   # this extracts 3 characters from index 3 to index 5  how 

h
i
how


In [ ]:
import random
secret_number = random.randint(1,100)
print(secret_number)

In [ ]:
from datetime import datetime
now = datetime.now()
print(f'Today is {now:%d-%b-%Y %H:%M}')

In [ ]:
from time import sleep

print("Hello")
sleep(10)
print("Hello again")

In [ ]:
from time import time

print('Enter your name in the quickest amount of time:')
start = time()    # Store the current time

name = input()
reaction_time = time() - start    # Calculate how much time has passed

print(f'You took {reaction_time:.2f} seconds') 


In [ ]:
from datetime import datetime
from dateutil import relativedelta as rdelta

date_of_birth = "17-08-1973"  # in string format
date_of_birth = datetime.strptime(date_of_birth, '%d-%m-%Y')  # datetime format
today = datetime.now()  # this is in datetime format

# Calculate diff
rd = rdelta.relativedelta(today,date_of_birth)

print(f"You were born on {date_of_birth:%d-%b-%Y}")
print(f"{rd.years} years, {rd.months} months and {rd.days} days since you were born")

# Practical Questions

In [ ]:
# 2-1 answer
name = input("What is your name :")
print("Hello",name)

In [ ]:
# 2-2 answer
weight = float(input(("Enter your weight: ")))
height = float(input(("Enter your height: ")))
print("Your BMI is:" + str(weight(height*height)))

In [1]:
# 2-3 answer
print("*"*60 + "\nCalculate the average electricity bill for the last 6 months\n" + "*"*60)
totalSum = 0
totalCount = 0
totalString = ""
for i in range(1,7):
    total = (float(input(f"Enter bill #{i}: ")))
    totalSum += total
    totalCount = i
    totalString += str(f"${total:.2f}, ")

print(f"\nYour electricity bill for the past 6 months are :\n{totalString[0:len(totalString)-2]}\n")
print(f"Your average electricity bill is ${(totalSum/totalCount):.2f}")

************************************************************
Calculate the average electricity bill for the last 6 months
************************************************************

Your electricity bill for the past 6 months are :
$23.00, $23.00, $23.00, $24.00, $24.00, $24.00

Your average electricity bill is $23.50


In [ ]:
# 2-3 answer
print("*"*60 + "\nCalculate the average electricity bill for the last 6 months\n" + "*"*60)
totalSum = 0
totalCount = 0
totalString = ""
for i in range(0, 6):
    total = float(input(f"Enter bill #{i+1}: "))
    totalSum += total
    totalCount = i + 1
    totalString += str(f"${total:.2f}, ")

print(totalCount)
print(f"Your electricity bill for the past {totalCount} months are :\n{totalString[0:len(totalString)-2]}\n")
print(f"Your average electricity bill is ${(totalSum/totalCount):.2f}")

In [ ]:
# 3-1 answer 
from time import sleep

time_to_wait = int(input("Enter the number of seconds to count down: "))
print(f"Let's count down {time_to_wait} seconds now...")
sleep(time_to_wait)
print("Time is up!")

In [ ]:
# 3-2 answer
from time import time

print('Timer starts now! Press any key as quickly as possible: ')
# stores the current time
time_now = time()

user_input = input()
# stores the time for people to enter
time_entered = time()

# calc time diff
time_response = time() - time_now    # Calculate how much time has passed

print(f'You took {time_entered} seconds to type {user_input}') 

In [ ]:
# 4-1 answer
n1 = int(input("Enter number 1: "))
n2 = int(input("Enter number 2: "))
n3 = int(input("Enter number 3: "))
n4 = int(input("Enter number 4: "))
sum = n1 + n2 + n3 + n4
difference = n1 - n4
product = n2 * n3
quotient = (n1 + n2)/(n3 + n4)
remainder = (n1 * n2) % (n3 * n4)
power = n1**n2

print(f"The four numbers are {n1} {n2} {n3} {n4}")
print(f"Sum is {sum}")
print(f"Difference is {difference}")
print(f"Product is {product}")
print(f"Quotient is {quotient}")
print(f"Remainder is {remainder}")
print(f"Power is {power}")

In [ ]:
# 4-2 answer
import math
print("*"*60 + "\nMathematical calculations with Python\n" + 60*"*" +"\n\n")

n1 = float(input("Enter number 1:"))
n2 = float(input("Enter number 2:"))
n3 = float(input("Enter number 3:"))
n4 = float(input("Enter number 4:"))
n1_squareroot = math.sqrt(n1)
n2_times_pi = math.pi * n2
n3_powerof_n1 = math.pow(n3, n1)
n4_factorial = math.factorial(n4)
n4n3 = n4_factorial / n3

print(f"The square root of {n1} is {n1_squareroot}")
print(f"The ceiling value of n1_squareroot is {math.ceil(n1_squareroot)}")

print(f"\n{n2} times {math.pi} is {n2_times_pi}")
print(f"The truncated value of n2_times_pi is {math.trunc(n2_times_pi)}")

print(f"\n{n3} to the power of {n1} is {n3_powerof_n1}")
print(f"The floor value of n3_powerof_n1 is {math.floor(n3_powerof_n1)}")

print(f"\n{n4} factorial is {n4_factorial}")
print(f"{n4_factorial} divided by {n3} is {n4n3}")
print(f"The fractional value of the result is {math.modf(n4n3)[0]}")
print(f"The integer value of the result is {math.modf(n4n3)[1]}")

In [ ]:
#s1 = "Mary had a little lamb"
#s2 = "To be or not to be"
#s3 = "that is the question"
s1 = input("Enter string 1")
s2 = input("Enter string 2")
s3 = input("Enter string 3")
print(f"Length of string 1 {s1} is {len(s1)}")
print(f"Length of string 2 {s2} is {len(s2)}")
print(f"Length of string 3 {s3} is {len(s3)}")
print(f"String 1 in all caps {s1.upper()}")
if ("a" in s2):
    print(f"The letter a is found in {s2}")
else :
    print(f"The letter a is not found in {s2}")
print(f"The first two character of {s3} is {s3[0:2]}")

In [ ]:
# 5-2 answer
stringValue = input("Enter 3 random strings, separated by commas: ")

[s1, s2 ,s3] = stringValue.split(",")

print(f"\ns1 is {s1}")
print(f"Length of {s1} is {len(s1)}")
print(f"2nd and 3rd characters of {s1} is {s1[1:3]}")

print(f"\ns2 is {s2}")
print(f"Length of {s2} is {len(s2)}")
print(f"5th and 7th characters of {s2} is {s2[4:7]}")

print(f"\ns3 is {s3}")
print(f"Length of {s3} is {len(s3)}")
print(f"Last two characters of {s3} is {s3[len(s3)-2:len(s3)]}")

In [ ]:
# 6-1 answers
print("*"*60 + "\nSection 6 - if-else statement\n" + 60*"*" +"\n\n")

userInput = input("Enter a number: ")
if (userInput.isnumeric()):
    if(int(userInput)%2==0):
        print(f"{userInput} is even")
    else:
        print(f"{userInput} is odd")
else:
    print("You did not enter a number")

In [ ]:
# 6-2 answers
menu = {1: ('SPMuffin', 5.00), 2: ('SPanCakes', 3.00), 3: ('SPHashbrown', 1.50)}

print("Welcome to SPdonalds!\nBelow is our Breakfast menu:\n" + "1.SPMuffin ($5.00) 2.SPancakes ($3.00) 3.SPHashbrown ($1.50)")
userInput = input("Enter your choice food:")

if(userInput.isnumeric()):
    userIntInput = int(userInput)
    if(userIntInput in menu):
        print(f'{menu.get(userIntInput)[0]} ${menu.get(userIntInput)[1]:.2f} added!')
        numberOfOrders = int(input(f"How many {menu.get(userIntInput)[0]} do you want to order? "))
        print(f'The total cost for {menu.get(userIntInput)[0]} is ${numberOfOrders * menu.get(userIntInput)[1]:.2f}')
    else:
        print("Sorry, you have entered an invalid choice. Exiting program...")
else:
    print("Please key in an actual number!")
    
    #object that has a method to return the next member, internally has a counter. next time it just +1 so the next function will
    #return the val

In [ ]:
# 7-1 answers
userMessage = input("Enter the message your want to repeat: ")
numberOfLoops = int(input("Enter the number of times you want to repeat this message: "))

for i in range(0,numberOfLoops):
    print(userMessage)

In [12]:
# 7-2 answers
print(f'This program prints the sum of a range of numbers from x to y\nFor example,if x is 10 and y is 50, the program will print the sum of numbers from 10 to 50')
x = input("Please enter the value of x: ")
y = input("Please enter the value of y: ")

if x.strip('-').isnumeric() and y.strip('-').isnumeric():
    x = int(x)
    y = int(y)
    if (x == 0 or y == 0):
        print("One or more of your inputs are not greater than zero!\nUnable to continue. Program terminated.")
    elif(x > y):
        print("You did not enter a value of y that is greater than x\nUnable to continue. Program terminated.")
    else:
        sum_of_numbers = 0
        for i in range (x, y + 1):
            sum_of_numbers += i
        print(f"The sum of numbers between {x} and {y} is {sum_of_numbers}")
else:
    print("One or more of your inputs are not numeric!\nUnable to continue. Program terminated.")

This program prints the sum of a range of numbers from x to y
For example,if x is 10 and y is 50, the program will print the sum of numbers from 10 to 50
Please enter the value of x: -5
Please enter the value of y: -3
The sum of numbers between -5 and -3 is -12


In [ ]:
# 8-1 answers
from time import sleep

userInput = int(input("Enter the number of seconds to count down: "))
while(userInput != 0):
    sleep(1)
    userInput += - 1
    print(f'{userInput} seconds till the timer expires')

print("Time is up!")

In [3]:
# 8-2
import random

print("This program will generate a random number between a lower limit and upper limit fo your choice:")
lower_limit = int(input("Enter the lower limit: "))
upper_limit = int(input("Enter the upper limit: "))
secret_number = random.randint(lower_limit,upper_limit)

user_guess = int(input(f"Enter your guess ({lower_limit} to {upper_limit}): "))
while(user_guess != secret_number):
    if(user_guess > secret_number):
        print("Too high")
    else:
        print("Too low")
        
    user_guess = int(input(f"Enter your guess ({lower_limit} to {upper_limit}): "))
    
print("You are right!")

This program will generate a random number between a lower limit and upper limit fo your choice:
Enter the lower limit: 1
Enter the upper limit: 2
Enter your guess (1 to 2): 1
You are right!


In [2]:
# 9-1 Lists
aList = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
stringList = "\n"
for number in aList:
    if(number < 5):
        stringList += str(number) + "\n"

print(f'Item less than 5 are {stringList}')

Item less than 5 are 
1
1
2
3



In [1]:
# 9-2 Lists (max, min, sorted, reverse)
list = []
for i in range(0,5):
    list.append(int(input(f"Enter number {i+1}: ")))

maximum = list[0]
minimum = list[0]

for number in list:
    if(number > maximum):
        maximum = number
    
    if(minimum > number):
        minimum = number
        
    
        
print(f"Maximum of the numbers is {maximum}")
print(f"Minimum of the numbers is {minimum}")
print(f"The original list is {list}")
list.sort()
print(f"The sorted list in reverse order is {list[::-1]}")

Enter number 1: 1
Enter number 2: 2
Enter number 3: 3
Enter number 4: 4
Enter number 5: 5
Maximum of the numbers is 5
Minimum of the numbers is 1
The original list is [1, 2, 3, 4, 5]
The sorted list in reverse order is [5, 4, 3, 2, 1]


In [15]:
 #9-3: List Slicing (SUBMISSION REQUIRED)
list_1 = [300, 50, 80, 90, 199, 800, 74, 33]
list_2 = ['Apple', 'Banana', 'Durian', 'Grapes', 'Papaya', 'Watermelon']
list_3 = [0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]

print(f'{list_1[len(list_1)-3:len(list_1)]}')
print(f'{list_2[len(list_2)-2:len(list_2)]}')
print(f'{list_3[1:len(list_3)-1]}')

[800, 74, 33]
['Papaya', 'Watermelon']
[1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8]


In [8]:
 #10-2: Odd and Even (SUBMISSION REQUIRED)
import random
    
original_list = [random.randint(1,100) for x in range(0,20)]

def oddandeven(numbers_list):
    even_numbers =[]
    odd_numbers=[]
    for number in original_list:
        if(number % 2 == 0):
            even_numbers.append(number)
        else:
            odd_numbers.append(number)

    return even_numbers, odd_numbers
    
[d1, d2] = oddandeven(original_list)
print("Original list:",original_list)
print("Even:",d1)
print("Odd:",d2)

Original list: [24, 27, 98, 12, 57, 77, 14, 60, 11, 55, 18, 28, 22, 83, 28, 75, 51, 20, 44, 5]
Even: [24, 98, 12, 14, 60, 18, 28, 22, 28, 20, 44]
Odd: [27, 57, 77, 11, 55, 83, 75, 51, 5]


In [10]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7, 8, 9]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [17]:
import numpy as np
sudo = np.array([[1, 2, 3],
                 [4, 5, 6], 
                 [7, 8, 9]])
print(sudo[0][0])

1


In [23]:
import numpy as np

# Create 2 arrays with different data types, shapes and sizes
a = np.array([10,2,8,4,6,1,5,9,3,7])
b = np.array([("Red","Blue","Yellow"),("Green","Cyan","Magenta")])

a.sort()
b.sort(axis=1)#column

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[['Blue' 'Red' 'Yellow']
 ['Cyan' 'Green' 'Magenta']]


In [26]:
c = np.array([1,2,3,4,5],dtype=np.bool)
print(c)

[ True  True  True  True  True]
<ipython-input-26-b0ad7e7a2958>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  c = np.array([1,2,3,4,5],dtype=np.bool)


In [27]:
import numpy as np

# Create 3 arrays with different shapes
a = np.array([1,2,3])
b = np.array([(1,2,3),(4,5,6)])
c = np.array([[(1,2,3,4),(5,6,7,8)], [(9,10,11,12),(13,14,15,16)]])

#shape returns the number of elements in each dimension
print(a.shape)

print(b.shape)

print(c.shape)


(3,)
(2, 3)
(2, 2, 4)


In [29]:
import numpy

my_array = numpy.array([1,2,3,4,5,6])
print(my_array)
print()
print(numpy.reshape(my_array,(3,3)))


[1 2 3 4 5 6]



ValueError: cannot reshape array of size 6 into shape (3,3)

In [31]:
import numpy as np

x = np.array(([10,20,30], [40,50,60]))
y = np.array(([1,2,3], [4,5,6]))

print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)





[[10 20 30]
 [40 50 60]]
[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [44 55 66]]
[[ 9 18 27]
 [36 45 54]]
[[ 10  40  90]
 [160 250 360]]
[[10. 10. 10.]
 [10. 10. 10.]]
[[0 0 0]
 [0 0 0]]


In [32]:
import numpy as np

a = np.arange(6).reshape(2,3)
b = a % 2 == 0
a = a[b]

print(a)


[0 2 4]


In [34]:
import numpy as np

# Create an array with 0 to 23 and reshape it into a 2x3x4 array# Think of it as an Excel workbook with 2 worksheets
# Each worksheet has 3 rows,4 columns
b = np.arange(24).reshape(2,3,4)
print(b[0,:,-1])  #3 7 11


[ 3  7 11]


In [49]:
import datetime
age = int(input("Enter your age"))

today = datetime.datetime.today()
print("We are now in year {}".format(today.year))
yearofbirth= today.year - age
print("You were born in the year {}".format(yearofbirth))

We are now in year 2021
You were born in the year 1989


In [37]:
spam = "7"
spam = spam + "0"
eggs = int(spam)+3
print(float(eggs))

73.0


In [39]:
for i in range(1,11):
    print("Image{}".format(i))

Image1
Image2
Image3
Image4
Image5
Image6
Image7
Image8
Image9
Image10


In [41]:
def myFunction(s):
    s = s*2
    return s


print(myFunction("Hello"))

HelloHello


In [42]:
def myFunction(s):
    s = s*2
    return s


print(myFunction("Hello"))

HelloHello


In [43]:
def myFunction(s):
    s = s*2
    return s


print(myFunction("Hello"))

HelloHello


In [45]:
import numpy as np

list1 = np.arange(20,30,2)
print(list1)

[20 22 24 26 28]


In [47]:
def shortest_string(x,y):
    if len(x) <= len(y):
        return x
    else:
        return y

s1 = "Hello"
s2= "Hi"

print(shortest_string(s1,s2))  # Prints Hi

Hi


In [48]:
import numpy as np

s = np.arange(13)**2
print(s[3:7])

[ 9 16 25 36]


In [56]:

def getGrade(marks):
    if marks>=80:
        return 'Distinction'
    elif marks>=70:
        return 'Merit'
    elif marks >= 50:
       return 'Pass'
    else:
       return 'Fail'

print(getGrade(30)) # Prints Fail
print(getGrade(75)) # Prints Merit
print(getGrade(50)) # Prints Pass
print(getGrade(83)) # Prints Distinction



Fail
Merit
Pass
Distinction


In [57]:
str = "To be or not to be, that is the question"

print(str[3:7])

be o
