In [2]:
import numpy as np
import pandas as pd

In [6]:
data = np.genfromtxt("coe-results.csv",
                    delimiter=",",
                    names=True, dtype=('U7', int, 'U10', int, int, int, int))

print("{} rows".format(len(data)))

1230 rows


In [3]:
print(len(data))

1230


In [4]:
print(data[0])

('2010-01', 1, 'Category A', 1152, 1145, 1342, 18502)


In [5]:
print(len(data[0]))

7


In [6]:
print(np.unique(data['vehicle_class']))

['Category A' 'Category B' 'Category C' 'Category D' 'Category E']


In [7]:
print(np.unique(data['month']))

['2010-01' '2010-02' '2010-03' '2010-04' '2010-05' '2010-06' '2010-07'
 '2010-08' '2010-09' '2010-10' '2010-11' '2010-12' '2011-01' '2011-02'
 '2011-03' '2011-04' '2011-05' '2011-06' '2011-07' '2011-08' '2011-09'
 '2011-10' '2011-11' '2011-12' '2012-01' '2012-02' '2012-03' '2012-04'
 '2012-05' '2012-06' '2012-07' '2012-08' '2012-09' '2012-10' '2012-11'
 '2012-12' '2013-01' '2013-02' '2013-03' '2013-04' '2013-05' '2013-06'
 '2013-07' '2013-08' '2013-09' '2013-10' '2013-11' '2013-12' '2014-01'
 '2014-02' '2014-03' '2014-04' '2014-05' '2014-06' '2014-07' '2014-08'
 '2014-09' '2014-10' '2014-11' '2014-12' '2015-01' '2015-02' '2015-03'
 '2015-04' '2015-05' '2015-06' '2015-07' '2015-08' '2015-09' '2015-10'
 '2015-11' '2015-12' '2016-01' '2016-02' '2016-03' '2016-04' '2016-05'
 '2016-06' '2016-07' '2016-08' '2016-09' '2016-10' '2016-11' '2016-12'
 '2017-01' '2017-02' '2017-03' '2017-04' '2017-05' '2017-06' '2017-07'
 '2017-08' '2017-09' '2017-10' '2017-11' '2017-12' '2018-01' '2018-02'
 '2018

In [8]:
print(data['premium'].mean())

42631.47398373984


In [9]:
print(data[data['premium'] > 20000])

[('2010-01', 2, 'Category A', 1151, 1149, 1673, 20501)
 ('2010-01', 2, 'Category B',  717,  717, 1105, 22400)
 ('2010-01', 2, 'Category C',  181,  173,  280, 20090)
 ('2010-01', 2, 'Category E',  588,  579, 1322, 21899)
 ('2010-02', 1, 'Category B',  693,  690,  930, 23180)
 ('2010-02', 1, 'Category C',  165,  162,  250, 21390)
 ('2010-02', 1, 'Category E',  601,  596, 1069, 22401)
 ('2010-02', 2, 'Category A', 1148, 1148, 1493, 20340)
 ('2010-02', 2, 'Category B',  685,  658,  956, 23889)
 ('2010-02', 2, 'Category C',  173,  170,  285, 23501)
 ('2010-02', 2, 'Category E',  590,  587, 1255, 24229)
 ('2010-03', 1, 'Category A', 1148, 1141, 1758, 20802)
 ('2010-03', 1, 'Category B',  688,  667, 1087, 26389)
 ('2010-03', 1, 'Category C',  168,  164,  257, 27001)
 ('2010-03', 1, 'Category E',  587,  575, 1184, 27590)
 ('2010-03', 2, 'Category A', 1146, 1137, 2183, 28389)
 ('2010-03', 2, 'Category B',  711,  699, 1207, 36089)
 ('2010-03', 2, 'Category C',  168,  141,  341, 32890)
 ('2010-03

# Slides

In [10]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([(1, 2, 3), (4, 5, 6)])
c = np.array(["Apple", "Orange", "Pear", "Durian"])

print(a)
print(b)
print(c)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
['Apple' 'Orange' 'Pear' 'Durian']


In [11]:
a = np.arange(1.1,11.1).reshape(2,5)

print(a)

[[ 1.1  2.1  3.1  4.1  5.1]
 [ 6.1  7.1  8.1  9.1 10.1]]


In [12]:
d = np.arange("2017-08-01","2017-09-01", dtype="datetime64")

print(d)

['2017-08-01' '2017-08-02' '2017-08-03' '2017-08-04' '2017-08-05'
 '2017-08-06' '2017-08-07' '2017-08-08' '2017-08-09' '2017-08-10'
 '2017-08-11' '2017-08-12' '2017-08-13' '2017-08-14' '2017-08-15'
 '2017-08-16' '2017-08-17' '2017-08-18' '2017-08-19' '2017-08-20'
 '2017-08-21' '2017-08-22' '2017-08-23' '2017-08-24' '2017-08-25'
 '2017-08-26' '2017-08-27' '2017-08-28' '2017-08-29' '2017-08-30'
 '2017-08-31']


In [13]:
d = np.linspace(0,2,9)
print(d)


[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [14]:
import numpy as np
h = np.random.randint(10,50,(3,2,4))
print(h)


[[[38 27 47 20]
  [42 40 38 14]]

 [[11 16 33 19]
  [17 44 42 37]]

 [[30 33 14 33]
  [27 44 42 44]]]


In [15]:
c = np.arange(10,20).reshape(2,5)
print(c)


[[10 11 12 13 14]
 [15 16 17 18 19]]


In [16]:
my_array = np.array([1,2,3,4,5,6])
print(my_array)
print()
print(my_array.reshape(2,3))


[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


In [17]:
# Create 3 arrays with different shapes
a = np.array([1,2,3])
b = np.array([(1,2,3),(4,5,6)])
c = np.array([[(1,2,3,4),(5,6,7,8)], [(9,10,11,12),(13,14,15,16)]])

#shape returns the number of elements in each dimension
print(a.shape)

print(b.shape)

print(c.shape)


(3,)
(2, 3)
(2, 2, 4)


# Practical

# Overall 3

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: Create 1-d numpy array

In [18]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
np.array(['Mary', 'John', 'Peter', 'Christine'])

array(['Mary', 'John', 'Peter', 'Christine'], dtype='<U9')

In [20]:
np.arange('2017-10-01','2017-11-01',dtype='datetime64')

array(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
       '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
       '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
       '2017-10-13', '2017-10-14', '2017-10-15', '2017-10-16',
       '2017-10-17', '2017-10-18', '2017-10-19', '2017-10-20',
       '2017-10-21', '2017-10-22', '2017-10-23', '2017-10-24',
       '2017-10-25', '2017-10-26', '2017-10-27', '2017-10-28',
       '2017-10-29', '2017-10-30', '2017-10-31'], dtype='datetime64[D]')

In [21]:
np.random.randint(0, 2, (10))

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1])

### Task 2: Create 2-d numpy array 

In [22]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
# x = np.arange(1.6, 1.9,0.1, dtype="float32")
x = np.array([1.6, 1.7, 1.8])
y = np.arange(2.5,10,2.5)
z = np.arange(20,80,20)

a = np.array([x,y,z], dtype="object")
print(a)

[[1.6 1.7 1.8]
 [2.5 5.0 7.5]
 [20 40 60]]


In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.full((4,3), 10.5)

array([[10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5]])

In [26]:
np.random.randint(1, 7, (4, 8))

array([[4, 1, 3, 3, 4, 3, 5, 4],
       [1, 3, 2, 6, 2, 2, 5, 6],
       [1, 3, 1, 3, 2, 1, 1, 6],
       [3, 4, 6, 6, 2, 3, 6, 4]])

# Overall 4

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: Use the  shape, ndim, size properties and len function

In [27]:
X = np.array([1.55,1.73,1.9,1.72,1.66,1.8])

print(f'The shape of X is {X.shape}')
print(f'The dimensions of X is {X.ndim}')
print(f'The size of X is {X.size}')
print(f'The length of X is {len(X)}')

The shape of X is (6,)
The dimensions of X is 1
The size of X is 6
The length of X is 6


In [28]:
Y = np.array([1.55,1.73,1.9,1.72,1.66,1.8])

print(f'The shape of Y is {Y.shape}')
print(f'The dimensions of Y is {Y.ndim}')
print(f'The size of Y is {Y.size}')
print(f'The length of Y is {len(Y)}')

The shape of Y is (6,)
The dimensions of Y is 1
The size of Y is 6
The length of Y is 6


In [29]:
Z = np.array([[(10,9,8,7),(6,5,4,3)], [(1,2,3,4),(5,6,7,8)]])

print(f'The shape of Z is {Z.shape}')
print(f'The dimensions of Z is {Z.ndim}')
print(f'The size of Z is {Z.size}')
print(f'The length of Z is {len(Z)}')

The shape of Z is (2, 2, 4)
The dimensions of Z is 3
The size of Z is 16
The length of Z is 2


# Overall 5

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: Flatten an array

In [30]:
a = np.array([ ['Mary', 'John','Bob'], 
               ['Zoe', 'Chris','Ann'],
               ['Leon', 'Kathy','Sam']])

np.resize(a,(1, a.size))


array([['Mary', 'John', 'Bob', 'Zoe', 'Chris', 'Ann', 'Leon', 'Kathy',
        'Sam']], dtype='<U5')

### Task 2: Reshape arrays

In [31]:
a = np.arange(15,30).reshape(3,5)
a.flatten()

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
b = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]]).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Task 3: Transpose array

In [33]:
a = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
print(a.transpose())

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


# Overall 6.	Manipulating Array Content

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: Concatenate arrays (SUBMISSION REQUIRED)

In [34]:
a = np.array([[1,2,3],[ 4,5,6],[7,8,9]])

b = np.full((3,3),1.5)

c = np.arange(0,15).reshape(5,3)

print(np.concatenate((a,b,c),axis=0))

[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 0.   1.   2. ]
 [ 3.   4.   5. ]
 [ 6.   7.   8. ]
 [ 9.  10.  11. ]
 [12.  13.  14. ]]


In [35]:
a = np.array([[1, 2,3,4],[ 4,5,6,7],[7,8,9,10],[11,12,13,14]])

b = np.random.randint(100,200,(4,6))

c = np.arange(0,40).reshape(4,10)

print(np.concatenate((a,b,c),axis=1))

[[  1   2   3   4 177 151 183 164 169 177   0   1   2   3   4   5   6   7
    8   9]
 [  4   5   6   7 148 131 140 163 115 100  10  11  12  13  14  15  16  17
   18  19]
 [  7   8   9  10 192 191 191 166 132 191  20  21  22  23  24  25  26  27
   28  29]
 [ 11  12  13  14 194 171 100 117 100 185  30  31  32  33  34  35  36  37
   38  39]]


### Task 2: Split arrays

In [36]:
x = np.arange(100)
y = np.split(x, 20)
print(y)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19]), array([20, 21, 22, 23, 24]), array([25, 26, 27, 28, 29]), array([30, 31, 32, 33, 34]), array([35, 36, 37, 38, 39]), array([40, 41, 42, 43, 44]), array([45, 46, 47, 48, 49]), array([50, 51, 52, 53, 54]), array([55, 56, 57, 58, 59]), array([60, 61, 62, 63, 64]), array([65, 66, 67, 68, 69]), array([70, 71, 72, 73, 74]), array([75, 76, 77, 78, 79]), array([80, 81, 82, 83, 84]), array([85, 86, 87, 88, 89]), array([90, 91, 92, 93, 94]), array([95, 96, 97, 98, 99])]


In [37]:
x = np.arange(100)
y = np.split(x,[10,25,45,75,95])
print(y)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]), array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44]), array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]), array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94]), array([95, 96, 97, 98, 99])]


# Overall 7.	Copying arrays

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: Make a copy of a Numpy array

In [38]:
x = np.array([1,2,3])
y = x
z = np.copy(x)

# if y is changed x is also changed because they are referencing the same memory
print(type(y))
# however, if z is changed, x wouldn't be affected because z created a new memory for itself
print(type(z))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [39]:
x = np.array([1, 2, 3])

y = x

z = np.copy(x)

x[0] = 10

print(x)
print(y)
print(z)

[10  2  3]
[10  2  3]
[1 2 3]


# Overall 8.	Sorting array
![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: Basic sorting (SUBMISSION REQUIRED)

In [40]:
arr_1 = np.random.randint(100,200,10)
print("**Before sorting**")
print(arr_1)

print("**After sorting**\n")
arr_1.sort()
print(arr_1)

**Before sorting**
[177 108 144 131 188 174 134 157 117 125]
**After sorting**

[108 117 125 131 134 144 157 174 177 188]


In [41]:
arr_2 = np.random.randint(1,20,(3,5))
print("**Before sorting**")
print(arr_2)

print("**After sorting**")
arr_2.sort(axis = 1)
print(arr_2)

**Before sorting**
[[18  6  6 10 11]
 [ 2 18 10  9  7]
 [10  1 11  4 19]]
**After sorting**
[[ 6  6 10 11 18]
 [ 2  7  9 10 18]
 [ 1  4 10 11 19]]


# Overall 9.	Subsetting and Indexing
![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: Basic subsetting

In [42]:
a = np.arange(1,100,1)
b = np.array([[1,2,3,4], [100,200,300,400],  [5,6,7,8],  [9,10,11,12] ])

# (a)	What is the output of a[3] and b[3]? What is the datatype of each output? - correct
# a[3] = 4
# b[3] = [9,10,11,12]
# print(a[3])
# print(b[3])

# (b)	Write Python code to print out 2nd and third rows of the array b (ie [100,200,300,400] and [5,6,7,8] - correct
# b[1:3]
# print(b[1:3])


# (c)	Write Python code to print out all the rows of the last column of array b
# b[0:4, -1]
# print(b[0:, 3:4])


# (d)	Write Python code to print out row 2 (i.e.[ 100,200,300,400], first  and last columns of array b
# b[1, [0, -1]]
# print(b[1, 0:4:3])


# (e)	Write Python code to print out row 3 to end, column 2 to end of the array b
# print(b[2:, 1:])
# print(b[2:, 1:])


# (f)	Write Python code to print out elements from index 10 to 20 with step 2 from array a
# print(a[10:20:2])


# (g)	Write Python code to select and reverse elements in array a from index 0 to the end, then print it out. - correct
# print(a[::-1])


### Task 2: Boolean indexing (SUBMISSION REQUIRED)

In [43]:
a = np.array((np.arange(0,10),
             np.arange(10,20),
             np.arange(20,30),
             np.arange(30,40)))

b = np.random.randint(100,200,(3,3))

print(a[a % 2 == 0])
print(b[b > 150])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[182 179 182 180]


In [44]:
b = np.arange(9.).reshape(3, 3)
b5 = np.where( b > 5 )

print("*** Values of where the elements, and their rows/columns")
for i in range(3):
    print(b[b5][i], "in row", b5[0][i], " column", b5[1][i])

*** Values of where the elements, and their rows/columns
6.0 in row 2  column 0
7.0 in row 2  column 1
8.0 in row 2  column 2


# Overall 10.	Array math
![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: Add, subtract, multiply and divide numpy arrays

In [45]:
a = np.arange(100,200,1).reshape(20,5) 
b = np.arange(1,2000,20).reshape(10,10) 
c = np.array([ [1,2,3], [4,5,6]])

In [46]:
# (a)	What happens when you try to perform the following operations on array a and array b?
# print(a+b)

In [47]:
# (b)	Create an array a2 that has the same shape as array a, containing random numbers between 0 and 100. 
# Print the contents of the resulting array when a and a2 are added together.
a2 = np.random.randint(0, 100, size = 100).reshape(20, 5)
print(a + a2)

b1 = b[0:2, 0:3]
print(b1 + c)

c2 = c * 10
print(c2)

[[110 123 168 193 164]
 [170 146 141 177 144]
 [175 169 200 137 150]
 [168 174 195 171 159]
 [165 138 179 197 186]
 [153 192 160 173 155]
 [169 208 154 146 210]
 [147 232 205 229 234]
 [152 149 160 208 233]
 [222 147 169 206 176]
 [213 198 198 209 252]
 [254 183 202 222 212]
 [243 198 248 188 166]
 [245 233 260 222 218]
 [231 259 188 213 272]
 [197 184 215 246 269]
 [224 235 254 221 227]
 [213 242 193 223 192]
 [246 235 271 283 277]
 [269 250 267 234 253]]
[[  2  23  44]
 [205 226 247]]
[[10 20 30]
 [40 50 60]]


# Overall 11.	Stastical method
![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: sum, mean (SUBMISSION REQUIRED)

In [48]:
a = np.array((np.arange(0,10),
             np.arange(10,20),
             np.arange(20,30),
             np.arange(30,40)))

# a
print("*** Sum of all numbers in a ***")
print(a.sum())

# b
print("\n*** Mean of all numbers in a ***")
print(a.mean())

# c
print("\n*** Sum of all numbers in a ***")
arrayStorage = a.sum(axis = 1)
for i in range (4):
    print(f"Row {i+1} = " + str(arrayStorage[i]))

*** Sum of all numbers in a ***
780

*** Mean of all numbers in a ***
19.5

*** Sum of all numbers in a ***
Row 1 = 45
Row 2 = 145
Row 3 = 245
Row 4 = 345


In [49]:
a = np.arange(100,200,0.5)
b = np.arange(100,200,0.1)

print(f"Contents of array a")
print(a)

print(f"Contents of array b")
print(b)

# standard deviation of arrays a and b?
print("\n** Standard Deviation **")
print(f"ST of a: " + str(a.std()))
print(f"ST of b: " + str(b.std()))

print("\n** Variance **")
print(f"VAR of a: " + str(a.var()))
print(f"VAR of b: " + str(b.var()))

Contents of array a
[100.  100.5 101.  101.5 102.  102.5 103.  103.5 104.  104.5 105.  105.5
 106.  106.5 107.  107.5 108.  108.5 109.  109.5 110.  110.5 111.  111.5
 112.  112.5 113.  113.5 114.  114.5 115.  115.5 116.  116.5 117.  117.5
 118.  118.5 119.  119.5 120.  120.5 121.  121.5 122.  122.5 123.  123.5
 124.  124.5 125.  125.5 126.  126.5 127.  127.5 128.  128.5 129.  129.5
 130.  130.5 131.  131.5 132.  132.5 133.  133.5 134.  134.5 135.  135.5
 136.  136.5 137.  137.5 138.  138.5 139.  139.5 140.  140.5 141.  141.5
 142.  142.5 143.  143.5 144.  144.5 145.  145.5 146.  146.5 147.  147.5
 148.  148.5 149.  149.5 150.  150.5 151.  151.5 152.  152.5 153.  153.5
 154.  154.5 155.  155.5 156.  156.5 157.  157.5 158.  158.5 159.  159.5
 160.  160.5 161.  161.5 162.  162.5 163.  163.5 164.  164.5 165.  165.5
 166.  166.5 167.  167.5 168.  168.5 169.  169.5 170.  170.5 171.  171.5
 172.  172.5 173.  173.5 174.  174.5 175.  175.5 176.  176.5 177.  177.5
 178.  178.5 179.  179.5 180.  

In [50]:
a = np.random.randint(1,1000,(3,4))

print(f"Contents of array a")
print(a)

A_R_Max = a.max(axis = 0)
print("\nMax a =", str(a.max()))
amax = np.where(a == a.max())
print(f"Row and column of " + str(a.max()) , "is ("+ str(amax[0]) + ", " + str(amax[1]) + ")")

A_C_Min = a.min(axis=1)
print("\nMin a =", str(a.min()))
amin = np.where(a == a.min())
print(f"Row and column of " + str(a.min()) , "is ("+ str(amin[0]) + ", " + str(amin[1]) + ")")

Contents of array a
[[432 664 767 562]
 [713 827 827 635]
 [255 254 136 379]]

Max a = 827
Row and column of 827 is ([1 1], [1 2])

Min a = 136
Row and column of 136 is ([2], [2])


# Overall 12.	File I/O on Numpy arrays
![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Task 1: Load a numpy array from a textfile (SUBMISSION REQUIRED)

In [51]:
filename = "singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv"
data = np.genfromtxt(filename,
                    delimiter=",",
                    names=True, dtype=('U4','U29', int))

In [55]:
# done
print(f"There are a altogether {len(data)} rows in the data file {filename}")

# done
data_years = data['year']
years = np.unique(data_years)
print(f"\nThere are {len(years)} years of data captured from {years[0]} to {years[-1]}")

# done
## Extract only the rows with Total Residents" - using boolean indexing
keyword = 'Total Residents'
data_totalresidents = data[data['level_1'] == keyword]

# done
### Print out the years which has the highest total number of residents 
max_residents = data_totalresidents['value'].max()
argmax_residents = data_totalresidents['value'].argmax()
print(f'\nYear with the highest total number of residents: {data_totalresidents[argmax_residents]["year"]}')
print(f'Population Count: {max_residents} ')

#done
### Print out the years which has the smallest total number of residents 
min_residents = data_totalresidents['value'].min()
argmin_residents = data_totalresidents['value'].argmin()
print(f'\nYear with the lowest total number of residents: {data_totalresidents[argmin_residents]["year"]}')
print(f'Population Count: { min_residents } ')

There are a altogether 855 rows in the data file singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv

There are 57 years of data captured from 1960 to 2016

Year with the highest total number of residents: 2016
Population Count: 3933559 

Year with the lowest total number of residents: 1960
Population Count: 1646400 
